AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
		- 'spec/*'
    - 'spec_answers/*'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
Layout/LineLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
  
